# Site settings
title: tintinplusplus.github.io
description: The Unoffiical TinTin++ User's Group

url: "http://tintinplusplus.github.io"
baseurl: ""
permalink: pretty

email: nathan.farrar@gmail.com
twitter_username: tintinplusplus
github_username:  tintinplusplus

gems:
  - jekyll-mentions
